/**
 * WhatsApp Service for Expense Tracker
 * Handles WhatsApp integration features
 */

class WhatsAppService {
    constructor() {
        this.isConfigured = false;
        this.userPhone = null;
        this.notificationsEnabled = false;
    }

    /**
     * Initialize WhatsApp service
     */
    async initialize() {
        try {
            const response = await ExpenseAPI.getWhatsAppStatus();
            if (response.success) {
                this.isConfigured = response.configured;
                this.userPhone = response.userPhone;
                this.notificationsEnabled = response.notificationsEnabled;
            }
        } catch (error) {
            console.log('WhatsApp service not available:', error.message);
        }
    }

    /**
     * Setup WhatsApp number for user
     */
    async setupWhatsApp(phoneNumber, enableNotifications = true) {
        try {
            const response = await ExpenseAPI.setupWhatsApp(phoneNumber, enableNotifications);
            if (response.success) {
                this.userPhone = response.phoneNumber;
                this.notificationsEnabled = response.notificationsEnabled;
                return { success: true, message: 'WhatsApp setup complete!' };
            }
            return { success: false, message: response.message };
        } catch (error) {
            return { success: false, message: error.message };
        }
    }

    /**
     * Send expense summary via WhatsApp
     */
    async sendSummary(period = 'month') {
        try {
            const response = await ExpenseAPI.sendWhatsAppSummary(period);
            return response;
        } catch (error) {
            return { success: false, message: error.message };
        }
    }

    /**
     * Send test message
     */
    async sendTestMessage() {
        try {
            const response = await ExpenseAPI.testWhatsApp();
            return response;
        } catch (error) {
            return { success: false, message: error.message };
        }
    }

    /**
     * Share expense report via WhatsApp Web (no API needed)
     */
    shareViaWhatsApp(text, phoneNumber = null) {
        let url = 'https://wa.me/';
        if (phoneNumber) {
            url += phoneNumber.replace(/[^0-9]/g, '');
        }
        url += '?text=' + encodeURIComponent(text);
        window.open(url, '_blank');
    }

    /**
     * Generate shareable expense summary text
     */
    generateSummaryText(expenses, period = 'This Month') {
        let text = `📊 *Expense Summary - ${period}*\n\n`;

        const total = expenses.reduce((sum, exp) => sum + exp.amount, 0);
        const byCategory = expenses.reduce((acc, exp) => {
            acc[exp.category] = (acc[exp.category] || 0) + exp.amount;
            return acc;
        }, {});

        text += `💰 *Total: ₹${total.toFixed(2)}*\n`;
        text += `📝 Expenses: ${expenses.length}\n\n`;

        text += `📁 *By Category:*\n`;
        Object.entries(byCategory)
            .sort((a, b) => b[1] - a[1])
            .forEach(([cat, amount]) => {
                text += `  • ${cat}: ₹${amount.toFixed(2)}\n`;
            });

        text += `\n_Generated by Expense Tracker_`;
        return text;
    }

    /**
     * Show WhatsApp settings modal
     */
    showSettingsModal() {
        const existingModal = document.getElementById('whatsappSettingsModal');
        if (existingModal) existingModal.remove();

        const modal = document.createElement('div');
        modal.id = 'whatsappSettingsModal';
        modal.className = 'modal-overlay';
        modal.innerHTML = `
            <div class="modal-content whatsapp-modal">
                <div class="modal-header">
                    <h2>📱 WhatsApp Settings</h2>
                    <button class="close-btn" onclick="whatsappService.closeSettingsModal()">&times;</button>
                </div>
                <div class="modal-body">
                    <div class="whatsapp-status ${this.isConfigured ? 'configured' : 'not-configured'}">
                        <span class="status-icon">${this.isConfigured ? '✅' : '⚠️'}</span>
                        <span>${this.isConfigured ? 'WhatsApp service is configured' : 'WhatsApp service not configured on server'}</span>
                    </div>

                    <div class="form-group">
                        <label for="whatsappPhone">Your WhatsApp Number</label>
                        <input type="tel" id="whatsappPhone" placeholder="+91 9876543210" value="${this.userPhone || ''}">
                        <small>Include country code (e.g., +91 for India)</small>
                    </div>

                    <div class="form-group checkbox-group">
                        <label>
                            <input type="checkbox" id="whatsappNotifications" ${this.notificationsEnabled ? 'checked' : ''}>
                            Enable expense notifications
                        </label>
                    </div>

                    <div class="button-group">
                        <button class="btn btn-primary" onclick="whatsappService.saveSettings()">
                            💾 Save Settings
                        </button>
                        <button class="btn btn-secondary" onclick="whatsappService.sendTestMessage().then(r => alert(r.message))">
                            📤 Send Test Message
                        </button>
                    </div>

                    <hr>

                    <h3>Quick Actions</h3>
                    <div class="quick-actions">
                        <button class="btn btn-outline" onclick="whatsappService.sendSummary('today').then(r => alert(r.message))">
                            📊 Send Today's Summary
                        </button>
                        <button class="btn btn-outline" onclick="whatsappService.sendSummary('week').then(r => alert(r.message))">
                            📅 Send Weekly Summary
                        </button>
                        <button class="btn btn-outline" onclick="whatsappService.sendSummary('month').then(r => alert(r.message))">
                            📆 Send Monthly Summary
                        </button>
                    </div>

                    ${!this.isConfigured ? `
                    <div class="setup-instructions">
                        <h3>⚙️ Server Setup Required</h3>
                        <p>To enable full WhatsApp integration, the server admin needs to configure Twilio credentials.</p>
                        <p>You can still use "Share via WhatsApp" feature without server setup!</p>
                    </div>
                    ` : ''}
                </div>
            </div>
        `;

        document.body.appendChild(modal);
        modal.addEventListener('click', (e) => {
            if (e.target === modal) this.closeSettingsModal();
        });
    }

    /**
     * Close settings modal
     */
    closeSettingsModal() {
        const modal = document.getElementById('whatsappSettingsModal');
        if (modal) modal.remove();
    }

    /**
     * Save WhatsApp settings
     */
    async saveSettings() {
        const phone = document.getElementById('whatsappPhone').value;
        const notifications = document.getElementById('whatsappNotifications').checked;

        if (!phone) {
            alert('Please enter your WhatsApp number');
            return;
        }

        const result = await this.setupWhatsApp(phone, notifications);
        alert(result.message);

        if (result.success) {
            this.closeSettingsModal();
        }
    }
}

// Global instance
const whatsappService = new WhatsAppService();
